GET http://10.5.0.4/api/v1/painters

###
GET http://10.5.0.4/api/v1/paints

###

POST http://10.5.0.4/api/v1/painters HTTP/1.1
content-type: application/json

{
    "Name": "Salvador Dali",
    "CityOfOrigin": "Figueres"
}

###

POST http://10.5.0.4/api/v1/paints HTTP/1.1
content-type: application/json

{
    "Name": "Living Still Life ",
    "CurrentLocation": "dunno",
    "PainterId": 2
}
