GET http://localhost:8080/api/v1/painters

###
GET http://localhost:8080/api/v1/paints

###
GET http://localhost:8080/comments

###

POST http://localhost:8080/api/v1/painters HTTP/1.1
content-type: application/json

{
    "Name": "Pedro Sanches3",
    "CityOfOrigin": "Valencia3"
}

###

POST http://localhost:8080/api/v1/paints HTTP/1.1
content-type: application/json

{
    "Name": "oretencia",
    "CurrentLocation": "carlota",
    "PainterId": 2
}
